### ISSUE TITLE
Please remove ff6347 as a CODEOWNER

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/oeffentliches-gestalten-gpt-search#48]
The user @ff6347 is listed in the CODEOWNERS file but should be removed.

**Comment by raphael-arce** [comment]
@ff6347 I didn't have the chance to look into this before, but as far as I can tell it has already been taken care of?

https://github.com/technologiestiftung/oeffentliches-gestalten-gpt-search/commit/dc87a1a8a095cf8a3fa61a8811ff1cec794d2876

**Comment by ff6347** [comment]
Jupp
